from readability_transformers.features.FeatureBase import FeatureBase, CustomFeatureExtractor
# from readability_transformers.features.LingFeat import LingFeat
from readability_transformers.features.TRUNAJODExtractor import TRUNAJODExtractor